# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [1]:
import numpy as np

np.__version__

'1.19.2'



---



## 배열 생성

### 리스트로 배열 만들기


In [5]:
import numpy as np

# 1차원
a1 = np.array([1,2,3,4,5])
a1
print(type(a1))
print(a1.shape)

<class 'numpy.ndarray'>
(5,)


In [7]:
import numpy as np

# 1차원
a1 = np.array([1,2,3,4,5])
print(a1.shape)
print(a1[0], a1[1])

(5,)
1 2


In [13]:
import numpy as np

# 1차원
a1 = np.array([1,2,3,4,5])
print(a1.shape) # 현재 1차원이기 때문에 뒤에는 쉼표

# 2차원
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a2.shape)

# 3차원
a3 = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[2,3,4], [5,6,7], [8,9,1]],
    [[3,4,5], [6,7,8], [9,1,2]]
])
print(a3.shape)

(5,)
(3, 3)
(3, 3, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [18]:
import numpy as np

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [19]:
np.full((3,4) , 1.2)

array([[1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [22]:
np.tri(5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [23]:
import numpy as np

np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [25]:
print(a1)
np.zeros_like(a1)

[1 2 3 4 5]


array([0, 0, 0, 0, 0])

In [27]:
np.ones_like(a2)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [28]:
np.full_like(a3, 5.5)

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [30]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [31]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [32]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [33]:
import numpy as np

np.random.random((3,3)) # shape만 지정 -> 실수 값으로 랜덤값 지정

array([[0.68174399, 0.19173601, 0.24160008],
       [0.9987094 , 0.99413262, 0.73324657],
       [0.57019245, 0.22492989, 0.89123622]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [34]:
np.random.randint(0, 10, (3,3)) # start, end , (shape) 지정해주어 랜덤 값 지정

array([[5, 8, 0],
       [8, 3, 4],
       [3, 2, 3]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [35]:
np.random.normal(0, 1, size=(4,4)) # 평균, 표준편차, (shape)

array([[ 0.37044309, -0.43016566, -0.30498136,  0.43865943],
       [ 1.38037939, -0.74143396,  1.99239946, -0.6742982 ],
       [ 0.76625532, -0.94287721,  0.15048021, -0.64382561],
       [-0.90051514, -0.21531278,  0.90915904,  0.71464407]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [36]:
np.random.rand(3,3) # rand는 uniform형태로 다른 값들과 일치하지 않는다

array([[0.36449238, 0.35971402, 0.53513792],
       [0.40426697, 0.7246721 , 0.2848347 ],
       [0.98305983, 0.9679546 , 0.1204094 ]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [37]:
np.random.randn(3, 3) # 표준정규분포를 고려한 배열로 생성

array([[-1.59443325,  0.05864123,  0.80218607],
       [ 0.01035857,  0.40467772,  1.21842439],
       [-0.20689974,  1.87914181,  0.35059977]])

### 표준 데이터 타입

In [40]:
import numpy as np

print(np.zeros(15, dtype = int))

print(np.ones((2,3), dtype = bool))

print(np.full((3,3), 1.0 ,dtype = float))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[ True  True  True]
 [ True  True  True]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 날짜/시간 배열 생성


In [42]:
import numpy as np

date = np.array('2020-01-01', dtype = np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [43]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [45]:
import numpy as np

datetime = np.datetime64('2020-01-01 12:00')
datetime 

numpy.datetime64('2020-01-01T12:00')



---



## 배열 조회

### 배열 속성 정보

In [50]:
def array_info(array):
    print(array)
    print("ndim: ", array.ndim) # 차원 출력
    print("shape: ", array.shape) # array shape
    print("type : ", array.dtype) # 배열의 데이터 타입
    print("size : ", array.size) # 배열의 개수 -> 크기
    print("itemsize : ", array.itemsize) # 각 하나의 아이템(원소)이 가지는 크기를 의미한다 (integer 32bit이기 때문에 4byte)
    print("nbytes : ", array.nbytes) # 전체 btye 크기 -> size * itemsize 값
    print("strides : ", array.strides) # 각 다음 차원으로 넘어가기 위한 사이즈 단위
    # 예를 들어 index = 0에서 1로 넘어갈때 필요한 바이트는 4byte


In [54]:
import numpy as np
a1 = np.array([1,2,3,4,5,6,7,8,10])
array_info(a1)

[ 1  2  3  4  5  6  7  8 10]
ndim:  1
shape:  (9,)
type :  int32
size :  9
itmesize :  4
nbytes :  36
strides :  (4,)


In [55]:
import numpy as np

# 2차원
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim:  2
shape:  (3, 3)
type :  int32
size :  9
itmesize :  4
nbytes :  36
strides :  (12, 4)


In [56]:
import numpy as np

# 3차원
a3 = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[2,3,4], [5,6,7], [8,9,1]],
    [[3,4,5], [6,7,8], [9,1,2]]
])
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[2 3 4]
  [5 6 7]
  [8 9 1]]

 [[3 4 5]
  [6 7 8]
  [9 1 2]]]
ndim:  3
shape:  (3, 3, 3)
type :  int32
size :  27
itmesize :  4
nbytes :  108
strides :  (36, 12, 4)


### 인덱싱(Indexing)

In [58]:
import numpy as np
# 1차원
a1 = np.array([1,2,3,4,5,6,7,8,10])

# 2차원
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

# 3차원
a3 = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[2,3,4], [5,6,7], [8,9,1]],
    [[3,4,5], [6,7,8], [9,1,2]]
])

In [59]:
print(a1)
print(a1[0])
print(a1[-1])
print(a1[3])
print(a1[5])

[ 1  2  3  4  5  6  7  8 10]
1
10
4
6


In [65]:
print(a2)
print(a2[0][0])
print(a2[-1][1])
print(a2[2][-2])
print(a2[-1][-2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
8
8
8


In [66]:
print(a3)
print(a3[0][0][1])
print(a3[-1][1][0])
print(a3[2][-2][2])
print(a3[-1][-2][-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[2 3 4]
  [5 6 7]
  [8 9 1]]

 [[3 4 5]
  [6 7 8]
  [9 1 2]]]
2
6
8
8


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [69]:
print(a1)
print(a1[0:2])
print(a1[-3: -1])
print(a1[::2])
print(a1[::-1])

[ 1  2  3  4  5  6  7  8 10]
[1 2]
[7 8]
[ 1  3  5  7 10]
[10  8  7  6  5  4  3  2  1]


In [72]:
print(a2)
print(a2[1, :])
print(a2[:2 , :2])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [74]:
print(a1)
bi = [False, True, False, True, True, False, True, False, True]
print(bi)
print(a1[bi])

[ 1  2  3  4  5  6  7  8 10]
[False, True, False, True, True, False, True, False, True]
[ 2  4  5  7 10]


In [76]:
print(a2)
bi = np.random.randint(0, 2, (3,3) , dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True False False]
 [False  True  True]
 [False  True False]]
[1 5 6 8]


### 팬시 인덱싱(Fancy Indedxing)

In [78]:
print(a1)
print([a1[0], a1[2]])
idx = [0, 4, 6]
print(a1[idx])

[ 1  2  3  4  5  6  7  8 10]
[1, 3]
[1 5 7]


In [79]:
ind = np.array([[0,1] , [2,0]])
print(a1[ind])

[[1 2]
 [3 1]]


In [81]:
print(a2)
row = np.array([0,2])
print(a2[row, :])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [82]:
import numpy as np
# 1차원
a1 = np.array([1,2,3,4,5,6,7,8,10])

# 2차원
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

# 3차원
a3 = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[2,3,4], [5,6,7], [8,9,1]],
    [[3,4,5], [6,7,8], [9,1,2]]
])

In [84]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
print(a1)

[ 1  2  3  4  5  6  7  8 10]
[10  1  2  3  4  5  6  7  8 10]
[ 1  2  3  4  5  6  7  8 10]


In [85]:
print(a2)
# 2 차원이므로 축을 지정해줄 수 있다
b2 = np.insert(a2, 1, 10, axis=0) # axis = 0은 행 방향으로 값 추가
c2 = np.insert(a2, 1, 10, axis=1) # axis = 1은 열 방향으로 값 추가
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [89]:
print(a1)
a1[0] = 3
a1[1] = 4
a1[2] = 5
print(a1)

a1[:1] = 9 # 슬라이싱에 포함되는 인덱스들을 해당 값으로 변환
print(a1)

i = np.array([1,3,4])
a1[i] = 0
print(a1)

a1[i] += 4
print(a1)

[ 9  0  5  0  0  6  7  8 10]
[ 3  4  5  0  0  6  7  8 10]
[ 9  4  5  0  0  6  7  8 10]
[ 9  0  5  0  0  6  7  8 10]
[ 9  4  5  4  4  6  7  8 10]


In [91]:
print(a2)
a2[0] = 0
print(a2) # 해당 행 전체 변경

a2[1:, 2] = 9
print(a2)

[[0 0 0]
 [4 5 6]
 [7 8 9]]
[[0 0 0]
 [4 5 6]
 [7 8 9]]
[[0 0 0]
 [4 5 9]
 [7 8 9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [93]:
print(a1)
b1 = np.delete(a1, 2)
print(b1)
print(a1) # 원본배열 값 변경  x!

[ 9  4  5  4  4  6  7  8 10]
[ 9  4  4  4  6  7  8 10]
[ 9  4  5  4  4  6  7  8 10]


In [94]:
print(a2)
b2 = np.delete(a2, 2, axis=0)
print(b2)
c2 = np.delete(a2, 2, axis=1)
print(c2)

[[0 0 0]
 [4 5 9]
 [7 8 9]]
[[0 0 0]
 [4 5 9]]
[[0 0]
 [4 5]
 [7 8]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [97]:
print(a2)
print(a2[:2, :2])

a2_sub = a2[:2, :2]
print(a2_sub)
a2_sub[:, 1] = 0
print(a2_sub)
print(a2) # 원본 배열도 0으로 바뀜 -> sub로 슬라이싱 영향 끼침

[[0 0 0]
 [4 0 9]
 [7 8 9]]
[[0 0]
 [4 0]]
[[0 0]
 [4 0]]
[[0 0]
 [4 0]]
[[0 0 0]
 [4 0 9]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [99]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2) # 안바뀜!

[[0 0 0]
 [4 0 9]
 [7 8 9]]
[[0 0]
 [4 0]]
[[0 1]
 [4 1]]
[[0 0 0]
 [4 0 9]
 [7 8 9]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [100]:
import numpy as np
# 1차원
a1 = np.array([1,2,3,4,5,6,7,8,10])

# 2차원
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

# 3차원
a3 = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[2,3,4], [5,6,7], [8,9,1]],
    [[3,4,5], [6,7,8], [9,1,2]]
])

In [101]:
print(a2)
print(a2.T) # 행렬 전치

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [102]:
print(a2)
print(a2.swapaxes(1,0)) # T와 동일 결과 출력

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [103]:
print(a3)
print(a3.swapaxes(1,0))
print(a3.swapaxes(2,0))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[2 3 4]
  [5 6 7]
  [8 9 1]]

 [[3 4 5]
  [6 7 8]
  [9 1 2]]]
[[[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]
  [6 7 8]]

 [[7 8 9]
  [8 9 1]
  [9 1 2]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[2 3 4]
  [5 6 7]
  [8 9 1]]

 [[3 4 5]
  [6 7 8]
  [9 1 2]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [104]:
n1 = np.arange(1, 10) 
print(n1) # 1차원
print(n1.reshape((3,3))) #2차원으로 변경

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [105]:
print(n1)
print(n1[np.newaxis, :5]) # 행에 축 추가
print(n1[:5, np.newaxis]) # 열에 축 추가

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [106]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
# size 크기 변경 x , 모양만 바뀜
n2.resize((5,2))
print(n2)

[[7 8 5 9 2]
 [4 5 2 0 7]]
[[7 8]
 [5 9]
 [2 4]
 [5 2]
 [0 7]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [107]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
# size 크기 변경 o , 모양만 바뀜
n2.resize((5,5))
print(n2)

[[2 8 1 6 6]
 [8 9 3 9 8]]
[[2 8 1 6 6]
 [8 9 3 9 8]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [108]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
# size 크기 변경 o , 모양만 바뀜
n2.resize((3,3))
print(n2) # 원래 10개 원소 있는데 여기서 1개 삭제됨

[[9 0 0 0 3]
 [7 4 3 3 7]]
[[9 0 0]
 [0 3 7]
 [4 3 3]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [111]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.arange(10, 19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [112]:
c2 = np.append(a2, b2)
# 1차원으로 변형 -> append는 axis지정 없으면 1차원 형태로 변형하여 결합함.
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [114]:
c2 = np.append(a2, b2, axis=0) # 행에 b2부분이 append됨
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [115]:
c2 = np.append(a2, b2, axis=1) # 열에 b2부분이 append됨
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [117]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
print(np.concatenate([a1, b1]))

[1 3 5 2 4 6]


In [118]:
c1 = np.array([7, 8, 9])
print(np.concatenate([a1, b1, c1]))

[1 3 5 2 4 6 7 8 9]


In [120]:
a1 = np.array([[1,2,3],
              [4,5,6]])
print(np.concatenate([a1, a1])) # 밑에 붙음
print(np.concatenate([a1, a1], axis=1))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [121]:
np.vstack([a2, a2]) # 밑(수직)으로 붙늗나

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [122]:
np.hstack([a2, a2]) # 옆(수평)으로 붙늗나

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [123]:
np.dstack([a2,a2]) # 깊이로 붙는다

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]],

       [[7, 7],
        [8, 8],
        [9, 9]]])

* `stack()`: 새로운 차원으로 연결

In [124]:
np.stack([a2, a2]) # 새로운 차원을 추가해서 연결

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

### 배열 분할

* `split()`: 배열 분할

In [129]:
import numpy as np
a1 = np.arange(0, 10)
print(a1)

# b1, c1 = np.split(a1, [5])
# print(b1, c1)

d = np.split(a1, [2,4,6,8])
print(d)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [133]:
import numpy as np
a1 = np.arange(1, 10).reshape(3,3)
print(a1)

b1, c1 = np.vsplit(a2, [2])
print("b1 : ",b1)
print("c1 : ",c1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
b1 :  [[1 2 3]
 [4 5 6]]
c1 :  [[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [135]:
import numpy as np
a1 = np.arange(1, 10).reshape(3,3)
print(a1)

b1, c1 = np.hsplit(a1, [2])
print("b1 : ",b1)
print("c1 : ",c1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
b1 :  [[1 2]
 [4 5]
 [7 8]]
c1 :  [[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [136]:
import numpy as np
a1 = np.arange(1, 28).reshape(3,3,3)
print(a1)

b1, c1 = np.dsplit(a1, [2])
print("b1 : ",b1)
print("c1 : ",c1)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
b1 :  [[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
c1 :  [[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [137]:
import numpy as np

a1 = np.arange(3)
print(a1)
print(a1 + 5)

[0 1 2]
[5 6 7]


In [139]:
a2 = np.ones((3,3))
print(a2)
print(a2 + np.arange(3))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [140]:
import numpy as np
a3 = np.arange(3).reshape(3, 1)
a4 = np.arange(3)
print(a3)
print(a4)
print(a3+a4)

[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


### 산술 연산(Arithmetic Operators)

In [144]:
a1 = np.arange(1, 10)
print(a1)

# 덧셈
print(a1 + 10)
print(np.add(a1, 10))
print("\n")

# 뺄셈
print(a1 - 2)
print(np.subtract(a1, 2))
print("\n")

# 단항 음수
print(-a1)
print(np.negative(a1))
print("\n")

# 곱셈
print(a1 * 2)
print(np.multiply(a1, 2))
print("\n")

# 나눗셈
print(a1 / 2)
print(np.divide(a1, 2))
print("\n")

# 나눗셈 내림
print(a1 * 2)
print(np.multiply(a1, 2))
print("\n")

# 지수 연산
print(a1 ** 2)
print(np.power(a1, 2))
print("\n")

# 나머지 연산
print(a1 % 2)
print(np.mod(a1, 2))
print("\n")

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[11 12 13 14 15 16 17 18 19]


[-1  0  1  2  3  4  5  6  7]
[-1  0  1  2  3  4  5  6  7]


[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]


[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]


[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]


[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]


[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]




In [146]:
b1 = np.random.randint(1, 10, size=9)
print(a1)
print(b1)
print(np.multiply(a1, b1))

[1 2 3 4 5 6 7 8 9]
[5 7 2 9 7 4 7 7 1]
[ 5 14  6 36 35 24 49 56  9]


In [149]:
a2 = np.arange(1, 10).reshape(3,3)
b1 = np.random.randint(1, 10, size=(3,3))
print(a2)
print(b2)

print(a2+b2)
print(a2-b2)
print(a2*b2)
print(a2//b2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [151]:
import numpy as np

a1 = np.random.randint(-10, 10, size= 5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[-9  1 -9 -3 -7]
[9 1 9 3 7]
[9 1 9 3 7]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [153]:
import numpy as np

a1 = np.random.randint(-10, 10, size= 5)
print(a1)
print(np.square(np.abs(a1))) # 제곱
print(np.sqrt(np.abs(a1))) # 제곱근

[ 7 -6 -6  7 -7]
[49 36 36 49 49]
[2.64575131 2.44948974 2.44948974 2.64575131 2.64575131]


#### 지수와 로그 함수 (Exponential and Log Function)

In [154]:
import numpy as np

a1 = np.random.randint(1, 10, size= 5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1, 2))

[2 8 9 2 6]
[7.38905610e+00 2.98095799e+03 8.10308393e+03 7.38905610e+00
 4.03428793e+02]
[  4. 256. 512.   4.  64.]
[ 4 64 81  4 36]


In [155]:
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[0.69314718 2.07944154 2.19722458 0.69314718 1.79175947]
[1.        3.        3.169925  1.        2.5849625]
[0.30103    0.90308999 0.95424251 0.30103    0.77815125]


#### 삼각 함수(Trigonometrical Function)


In [157]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

x = [-1, 0, 1]
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))


[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [158]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))

print(a1)
print(a1.sum(), np.sum(a1))
print(a1.sum(axis=0), np.sum(a1, axis=0))

[[8 7 3]
 [4 5 4]
 [4 9 6]]
50 50
[16 21 13] [16 21 13]


#### cumsum(): 누적합 계산

In [160]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))

print(a1)
print("\n")
print(a1.cumsum(), np.cumsum(a1))
print("\n")
print(a1.cumsum(axis=0), np.cumsum(a1, axis=0))
print("\n")
print(a1.cumsum(axis=1), np.cumsum(a1, axis=1))

[[4 7 2]
 [7 8 7]
 [4 9 6]]


[ 4 11 13 20 28 35 39 48 54] [ 4 11 13 20 28 35 39 48 54]


[[ 4  7  2]
 [11 15  9]
 [15 24 15]] [[ 4  7  2]
 [11 15  9]
 [15 24 15]]


[[ 4 11 13]
 [ 7 15 22]
 [ 4 13 19]] [[ 4 11 13]
 [ 7 15 22]
 [ 4 13 19]]


#### diff(): 차분 계산

In [162]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))

print(a1)
print("\n")
print(np.diff(a1))
print("\n")
print(np.diff(a1, axis=0))
print("\n")
print(np.diff(a1, axis=1))

[[3 5 7]
 [9 6 4]
 [4 2 5]]


[[ 2  2]
 [-3 -2]
 [-2  3]]


[[ 6  1 -3]
 [-5 -4  1]]


[[ 2  2]
 [-3 -2]
 [-2  3]]


#### prod(): 곱 계산

In [163]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))

print(a1)
print("\n")
print(np.prod(a1))
print("\n")
print(np.prod(a1, axis=0))
print("\n")
print(np.prod(a1, axis=1)) 

[[7 6 5]
 [2 8 6]
 [1 6 1]]


120960


[ 14 288  30]


[210  96   6]


#### cumprod(): 누적곱 계산

In [164]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))

print(a1)
print("\n")
print(np.cumprod(a1))
print("\n")
print(np.cumprod(a1, axis=0))
print("\n")
print(np.cumprod(a1, axis=1)) 

[[8 9 6]
 [7 2 6]
 [2 2 9]]


[      8      72     432    3024    6048   36288   72576  145152 1306368]


[[  8   9   6]
 [ 56  18  36]
 [112  36 324]]


[[  8  72 432]
 [  7  14  84]
 [  2   4  36]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [166]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))
b1 = np.ones_like(a1)

print(a1)
print(b1)
print("\n")
print(np.dot(a1, b1))
print("\n")
print(np.matmul(a1, b1))

[[5 4 6]
 [5 5 6]
 [2 3 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


[[15 15 15]
 [16 16 16]
 [14 14 14]]


[[15 15 15]
 [16 16 16]
 [14 14 14]]


#### tensordot(): 텐서곱 계산

In [169]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))
b1 = np.ones_like(a1)

print(a1)
print(b1)
print("\n")
print(np.tensordot(a1, b1))
print("1.\n")
print(np.tensordot(a1, b1, axes=0))
print("2.\n")
print(np.tensordot(a1, b1, axes=1))

[[2 6 4]
 [4 3 3]
 [1 4 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


29
1.

[[[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]]


 [[[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]]]
2.

[[12 12 12]
 [10 10 10]
 [ 7  7  7]]


#### cross(): 벡터곱

In [170]:
import numpy as np
x = [1,2,3]
y = [4,5,6]

print(np.cross(x, y))
print("\n")

[-3  6 -3]




#### inner()/outer(): 내적/외적

In [173]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))
b1 = np.ones_like(a1)

print(a1)
print(b1)
print("\n")

print(np.inner(a1, b1)) # cross랑 동일 결과
print("\n")
print(np.outer(a1, b1))
print("\n")

[[8 1 5]
 [9 6 8]
 [5 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


[[14 14 14]
 [23 23 23]
 [ 7  7  7]]


[[8 8 8 8 8 8 8 8 8]
 [1 1 1 1 1 1 1 1 1]
 [5 5 5 5 5 5 5 5 5]
 [9 9 9 9 9 9 9 9 9]
 [6 6 6 6 6 6 6 6 6]
 [8 8 8 8 8 8 8 8 8]
 [5 5 5 5 5 5 5 5 5]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]




#### mean(): 평균 계산

In [174]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))

print(np.mean(a2)) # 모든 원소에서 최소
print(np.mean(a2 , axis = 0))
print(np.mean(a2 , axis = 1))

5.0
[4. 5. 6.]
[2. 5. 8.]


#### std(): 표준 편차 계산

In [175]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))

print(np.std(a2)) # 모든 원소에서 최소
print(np.std(a2 , axis = 0))
print(np.std(a2 , axis = 1))

2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


#### var(): 분산 계산

In [176]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))

print(np.std(a2)) # 모든 원소에서 최소
print(np.std(a2 , axis = 0))
print(np.std(a2 , axis = 1))

2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


#### min(): 최소값

In [177]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))

print(np.min(a2)) # 모든 원소에서 최소
print(np.min(a2 , axis = 0))
print(np.min(a2 , axis = 1))

1
[1 2 3]
[1 4 7]


#### max(): 최대값

In [178]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))

print(np.max(a2)) # 모든 원소에서 최소
print(np.max(a2 , axis = 0))
print(np.max(a2 , axis = 1))

9
[7 8 9]
[3 6 9]


#### argmin(): 최소값 인덱스

In [180]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))
print(a1)

print(np.argmin(a1)) # 모든 원소에서 최소
print(np.argmin(a1 , axis = 0))
print(np.argmin(a1 , axis = 1))

[[3 3 7]
 [9 1 7]
 [1 6 6]]
4
[2 1 2]
[0 1 0]


#### argmax(): 최대값 인덱스

In [181]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))
print(a1)

print(np.argmax(a1)) # 모든 원소에서 최소
print(np.argmax(a1 , axis = 0))
print(np.argmax(a1 , axis = 1))

[[8 4 6]
 [4 4 7]
 [8 9 1]]
7
[0 2 1]
[0 2 1]


#### median(): 중앙값

In [182]:
import numpy as np
a1 = np.random.randint(1, 10, size=(3,3))
print(a1)

print(np.median(a1)) # 모든 원소에서 최소
print(np.median(a1 , axis = 0))
print(np.median(a1 , axis = 1))

[[9 7 4]
 [4 8 7]
 [7 4 4]]
7.0
[7. 7. 4.]
[7. 7. 4.]


#### percentile(): 백분위 수



In [183]:
import numpy as np
a1 = np.array([0,1,2,3])
print(a1)
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='linear'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='higher'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='lower'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='nearest'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()

In [184]:
import numpy as np
a1 = np.array([[False, True, False],
              [False, False, False],
              [True, True, True]])
print(a1)
print(np.any(a1))
print(np.any(a1, axis=0))
print(np.any(a1, axis=1))

[[False  True False]
 [False False False]
 [ True  True  True]]
True
[ True  True  True]
[ True False  True]


#### all()

In [185]:
import numpy as np
a1 = np.array([[False, True, False],
              [False, False, False],
              [True, True, True]])
print(a1)
print(np.all(a1))
print(np.all(a1, axis=0))
print(np.all(a1, axis=1))

[[False  True False]
 [False False False]
 [ True  True  True]]
False
[False False False]
[False False  True]


### 비교 연산(Comparison Operators)


In [188]:
import numpy as np
a1 = np.arange(1, 10)
print(a1)
print("eqaul")
print(a1 == 5)
#print(np.equal(a1, 5))
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
eqaul
[False False False False  True False False False False]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [195]:
import numpy as np
a1 = np.arange(1, 10).reshape(3,3)
print(a1)

print(np.sum(a1))
print(np.sum(a1 > 5)) # count 5초과인 개수 세줘
print(np.count_nonzero(a1 > 5)) # count 5초과인 개수 세줘
print(np.sum(a1 > 5, axis=0)) # count 5초과인 개수 세줘
print(np.sum(a1 > 5, axis=1)) # count 5초과인 개수 세줘
print(np.any(a1 > 5, axis=0)) # count 5초과인 개수 세줘
print(np.all(a1 > 5, axis=1)) # count 5초과인 개수 세줘

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
[ True  True  True]
[False False  True]


In [200]:
import numpy as np
a1 = np.array([1,2,3,4,5])
print(a1)
b1 = np.array([1,2,3,3,4])
print(b1)
print(np.isclose(a1, b1)) # 값이 가까운건 True 아니면 False

a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1)) # 무한대 인거
print(np.isfinite(a1)) # 무한대 아닌거

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]
[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


In [202]:
import numpy as np
a1 = np.arange(1, 10).reshape(3, 3)
print(a2)
print((a2 > 5 ) & (a2 < 8))
print(a2[(a2 > 5 ) & (a2 < 8)]) # True인 부분만 추출됨 - 불리언 인덱싱

print((a2 > 5 ) | (a2 < 8))
print(a2[(a2 > 5 ) | (a2 < 8)]) # True인 부분만 추출됨 - 불리언 인덱싱

print((a2 > 5 ) ^ (a2 < 8))
print(a2[(a2 > 5 ) ^ (a2 < 8)]) # True인 부분만 추출됨 - 불리언 인덱싱

print(~(a2 > 5 ))
print(a2[~(a2 > 5 )]) # True인 부분만 추출됨 - 불리언 인덱싱

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


#### 불리언 연산자(Boolean Operators)


### 배열 정렬

#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

## 배열 입출력


sample_data




---

