### Norm 구현하기

Python Numpy를 이용하여 Norm을 구현할 수 있다. <br>
=> numpy에서 제공하는 linalg.norm 함수를 이용하여 Norm을 구한다!

**numpy.linalg.norm(x, ord=None, axis=None, keepdims=False)**

파라미터
* x = array(배열) / axis가 none이면 x는 1차원 or 2차원이다
* ord = 노름의 순서 => 차수
* axis = axis가 정수이면, 벡터 Norm을 계산할 x의 축을 지정 => 연산 방향
* keepdims = 이 값이 True이면 표준화된 축의 크기는 1이다. => 출력을 x와 동일한 차원 유지

In [11]:
import numpy as np
x = np.random.randint(low=1, high=10, size=(5,3))
# 행 5, 열 3
x

array([[1, 8, 9],
       [2, 5, 7],
       [6, 2, 3],
       [9, 2, 7],
       [8, 8, 5]])

In [13]:
L1_Norm = np.linalg.norm(x, axis=1, ord=1)
print(L1_Norm)
print("shape = ", L1_Norm.shape)

[18. 14. 11. 18. 21.]
shape =  (5,)


In [14]:
L2_Norm = np.linalg.norm(x, axis=1, ord=2)
print(L2_Norm)
print("shape = ", L2_Norm.shape)

[12.08304597  8.83176087  7.         11.5758369  12.36931688]
shape =  (5,)


### 행렬 tnsformation

In [2]:
import numpy as np

In [4]:
A = np.array([[-1, 2], [1, 1]]) # 기본 기조 벡터를 A 벡터로 변경
print(A)
B = np.array([3,2])
print(B)

print("transfortation : ", np.matmul(A, B))

[[-1  2]
 [ 1  1]]
[3 2]
transfortation :  [1 5]


In [5]:
print("X축 기저 벡터 : ", A[:, 0])
print("Y축 기저 벡터 : ", A[:, 1])

X축 기저 벡터 :  [-1  1]
Y축 기저 벡터 :  [2 1]


In [7]:
A = np.array([[-1, 2], [1, 1]]) # 기본 기조 벡터를 A 벡터로 변경
print(A)
B = np.array([[3, 1], [2, 3]])
print(B)

print("transfortation : ", np.matmul(A, B))

[[-1  2]
 [ 1  1]]
[[3 1]
 [2 3]]
transfortation :  [[1 5]
 [5 4]]


In [9]:
# 36개의 좌표들
P = [(x,y) for x in range(6) for y in range(6)]
P = np.array(P)
print(P)
print(P.T)

[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [0 5]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [2 5]
 [3 0]
 [3 1]
 [3 2]
 [3 3]
 [3 4]
 [3 5]
 [4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]
 [4 5]
 [5 0]
 [5 1]
 [5 2]
 [5 3]
 [5 4]
 [5 5]]
[[0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5]
 [0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5]]


In [10]:
# [2, 1], [1, 2] -> 기저 벡터
A = np.array([[2, 1], [1, 2]])
P2= np.matmul(P,A)
print(P2)
print(P2.T)

[[ 0  0]
 [ 1  2]
 [ 2  4]
 [ 3  6]
 [ 4  8]
 [ 5 10]
 [ 2  1]
 [ 3  3]
 [ 4  5]
 [ 5  7]
 [ 6  9]
 [ 7 11]
 [ 4  2]
 [ 5  4]
 [ 6  6]
 [ 7  8]
 [ 8 10]
 [ 9 12]
 [ 6  3]
 [ 7  5]
 [ 8  7]
 [ 9  9]
 [10 11]
 [11 13]
 [ 8  4]
 [ 9  6]
 [10  8]
 [11 10]
 [12 12]
 [13 14]
 [10  5]
 [11  7]
 [12  9]
 [13 11]
 [14 13]
 [15 15]]
[[ 0  1  2  3  4  5  2  3  4  5  6  7  4  5  6  7  8  9  6  7  8  9 10 11
   8  9 10 11 12 13 10 11 12 13 14 15]
 [ 0  2  4  6  8 10  1  3  5  7  9 11  2  4  6  8 10 12  3  5  7  9 11 13
   4  6  8 10 12 14  5  7  9 11 13 15]]
